#!/bin/csh
pushd /nfs/slac/g/exo/software/ROOT/rhel6/root/5.34.21/
source bin/thisroot.csh
popd
setenv LD_LIBRARY_PATH $NEXOANALYSIS/lib:${LD_LIBRARY_PATH}
cd $OUT_DIR

#printenv

date
echo "--> digitizing..."
# digitize:
time $NEXOANALYSIS/digitization/chargeDigitizer/bin/nEXOdigi -i $OUT_DIR/mc/runSEQNUM.root -lmap data2.root -t nEXOevents -o $OUT_DIR/digitization_dcoeffDIFF/digiSEQNUM_TYPE_dcoefDIFF.root -r SEED -n -1 -dcoef DIFF -wpFile TestStandWP.root -ids true -padsize 3 -indtype Ralph  >& $OUT_DIR/log/digi-TYPE-runSEQNUM_dcoefDIFFR.log

# remove old MC files:
rm $OUT_DIR/mc/runSEQNUM.root

date
echo "--> tier3 ..."
# tier3:
time python $CHARGEREADOUTSCRIPTS/generateTier3Files.py --MC -D $OUT_DIR/tier3/  $OUT_DIR/digitization_dcoeffDIFF/digiSEQNUM_TYPE_dcoefDIFF.root >& $OUT_DIR/log/tier3_SEQNUM.log

# remove old digi files:
rm $OUT_DIR/digitization_dcoeffDIFF/digiSEQNUM_TYPE_dcoefDIFF.root

